### ISSUE TITLE
deepKeys returns strange result

### ISSUE THREAD

**Issue by AuthorProxy** [sindresorhus/dot-prop#104]
```deepKeys({ x: 1, y: "1", z: [1], zz: [], o: {}, n: null, u: undefined, nan: NaN })```

returns

```['x', 'y', 'z[0]', 'n', 'u', 'nan']```

Why is it missing `zz` and `o`, for me it is looks as bug

**Comment by Richienb** [comment]
Working as intended. It would be inconsistent to only return the keys of arrays when and only when they are empty.

**Comment by sindresorhus** [comment]
@Richienb I look at it differently. All paths should be represented. Object/arrays are passthrough if the have children, but if not they are the path.
