### ISSUE TITLE
add possibility to use dot notation with arrays

### ISSUE THREAD

**Issue by AuthorProxy** [sindresorhus/dot-prop#107]
is it possible to add dot notation to arrays fields - `set\get\has`
now it works like this: `getProperty(obj, 'arr_field[1]')`
expected: `getProperty(obj, 'arr_field.1')`

It should work since array is just an object and it's easier to connect code with other libraries

**Comment by sindresorhus** [comment]
It's an intentional choice. We prefer having one way to do something and the `[0]` notation is more natural for users.
