### ISSUE TITLE
prop.get(user, 'name.first') will throw if name is null

### ISSUE THREAD

**Issue by matthewmueller** [sindresorhus/dot-prop#11]
Seems weird to me that this library throws on things like: `null`, `false`, `3`, `"hi"`.

I feel like the `obj === undefined` check should be `isObj(obj)` or something.

**Comment by stevemao** [comment]
Maybe we should check the accessibility of the property?

**Comment by sindresorhus** [comment]
Yeah, that's a bug. It should never throw no matter what you feed it. That's the whole point of this module.

**Comment by stevemao** [comment]
@sindresorhus do you want to support situation that a getter might throw? the only way is to `try... catch` it?

**Comment by sindresorhus** [comment]
Yes

**Comment by stevemao** [comment]
I think I know what you are going to say @sindresorhus , you probably just don't want to 'throw' from this module (and don't care too much about the performance) but the reason I try to avoid 'try...catch' and this module to 'throw' was to avoid regression.

**Comment by sindresorhus** [comment]
> and don't care too much about the performance

Throw doesn't have to mean worse performance. try/catch only deoptimizes the current function. If you put it in a helper function you're good.

**Comment by stevemao** [comment]
Ok, I'll get my Mac next Monday so seven more days if you guys don't mind waiting :)

**Comment by sindresorhus** [comment]
I can wait. I don't have time to look into this right now anyways.

**Comment by stevemao** [comment]
@matthewmueller @sindresorhus please review #12 :)
