### ISSUE TITLE
support of backslashes in properties?

### ISSUE THREAD

**Issue by hobbyquaker** [sindresorhus/dot-prop#15]
how to access a property like `'a\\b'`? 

these getter tests fail:
```javascript
t.is(m.get({'\\': true}, '\\\\'), true);
t.is(m.get({'a\\b': true}, 'a\\\\b'), true);
t.is(m.get({'fo\\.ob.az': {bar: true}}, 'fo\\\\\\.ob\\.az.bar'), true);
```

**Comment by SamVerschueren** [comment]
Escaping is only necessary when you want to escape a `.`. There is no regexp used in the implementation, so no need to escape a backslash.

```js
t.is(m.get({'a\\b': true}, 'a\\b'), true);
t.is(m.get({'fo\\.ob.az': {bar: true}}, 'fo\\\\.ob\\.az.bar'), true);
```

Not 100% sure why the `\\` key isn't working though.

**Comment by SamVerschueren** [comment]
Investigated it, and currently, having `\\` as key isn't supported. Will have a look at it if I find more time.

**Comment by hobbyquaker** [comment]
ok, thanks for the info!

**Comment by hobbyquaker** [comment]
hmm... just made up another nasty test ;-)

`t.is(m.get({'fo\\.ob.az\\': {bar: true}}, 'fo\\\\.ob\\.az\\.bar'), true);` fails. 

how can we differentiate escaped dots and simple backslashes in such a case?

**Comment by stevemao** [comment]
The code never unescape again. If it did `\.` would be unescaped as `.`. So this would be a new feature if we want to unescape the string.

**Comment by stevemao** [comment]
@hobbyquaker what's your use case? We could add something like "backslash can only escape `.`. There is no unicode escape..." to the docs.

**Comment by stevemao** [comment]
We need to state that `\` cannot escape anything else but `.` in readme.md

**Comment by stevemao** [comment]
Can you guys have a look at #17?

**Comment by sindresorhus** [comment]
Maybe worth looking into how Lodash.set/get handle this.

https://github.com/lodash/lodash/blob/2e790fb865d8c526ad7d90f725bd9b020d1bb3b6/lodash.js#L3426
