### ISSUE TITLE
Difference to lodash .set and .get?

### ISSUE THREAD

**Issue by mwittig** [sindresorhus/dot-prop#16]
I am just wondering about the differences between your package functions and the [.get](https://lodash.com/docs#get) and [.set](https://lodash.com/docs#set) functions of lodash. At a first glance it looks pretty much the same but I may have oberlooked something. Clarifying this might also help other users investigating your package. Note, lodash is also available as per-method packages. So it is possible to just to require lodash.get and lodash.set if one does not need the other 200 utility functions.

**Comment by sindresorhus** [comment]
I don't know. I haven't used those before.

**Comment by stevemao** [comment]
@mwittig There are many other similar modules, we can't compare all of them. Plus `lodash.get` and `lodash.set` are not very similar to this one IMO.

**Comment by mwittig** [comment]
Plus lodash.get and lodash.set are not very similar to this one IMO.
@stevemao This surprises me, Anyhow, thanks for the feedback.

For the lodash API doc:
``´
var object = { 'a': [{ 'b': { 'c': 3 } }] };

_.get(object, 'a[0].b.c');
// → 3

_.get(object, ['a', '0', 'b', 'c']);
// → 3

```

**Comment by stevemao** [comment]
If you look at the API docs you could easily see the difference.

**Comment by danawoodman** [comment]
One difference that was important for me was that `lodash.get` supports the ability to access an array element by index, eg:

```js
_.get(object, 'foo.bar[0].baz')
```
