### ISSUE TITLE
should dotProp.has({foo: undefined}, 'foo') be true ?

### ISSUE THREAD

**Issue by qiu8310** [sindresorhus/dot-prop#27]
```js
var a = {foo: undefined}

console.log(dotProp.has(a, 'foo'))  // false

console.log('foo' in a) // true
console.log(a.hasOwnProperty('foo'))  // true
```

**Comment by stevemao** [comment]
cc @thatjessicakelly

**Comment by sindresorhus** [comment]
Yes, that's a bug.

**Comment by stevemao** [comment]
@qiu8310 Can you try #29?

**Comment by qiu8310** [comment]
I wrote a different version [libs/lang/DotProp.js](https://github.com/qiu8310/mora-scripts/blob/master/libs/lang/DotProp.js), and test file [libs/lang/test/__DotProp.js](https://github.com/qiu8310/mora-scripts/blob/master/libs/lang/test/__DotProp.js).
 
Would you like to merge it?

**Comment by stevemao** [comment]
@qiu8310 if you can prove that implementation is better (we have good perf tests here) 😄
