### ISSUE TITLE
Consider renaming delete

### ISSUE THREAD

**Issue by LinusU** [sindresorhus/dot-prop#32]
`delete` is an operator in javascript and thus is a reserved keyword. That means that you can't have a variable named `delete` in any scope.

This also makes this module incompatible with [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) since you cannot have exports named `delete`.

I understand if you don't want to make this change, but I think it would be nice to rename the function to e.g. `del`. This would make the module ready for ES6 Modules 🚀

**Comment by sindresorhus** [comment]
`delete()` is a method on the main export. It's not an export itself though.

**Comment by SamVerschueren** [comment]
@sindresorhus I think what he means is that with ES6 modules you can have something like this

```
import { delete } from 'dot-prop';
```

Because `delete` now is a variable name and because `delete` is a reserved keyword, this is not allowed. Just guessing here though.

**Comment by sindresorhus** [comment]
Then you can rename it: `import {delete as del} from 'dot-prop'`. Those methods are not really meant to be used like that though. For example, with `import {get} from 'dot-prop'`, `get` could mean anything without the context.

**Comment by SamVerschueren** [comment]
I never used Rollup so not sure if this would work. I totally agree with you though, I would always use `import * as dotProp from 'dot-prop'`.

**Comment by LinusU** [comment]
I'm not entirely familiar with the internals of rollup, but currently it fails with this error:

> Error parsing dot-prop/index.js: Unexpected token (78:4) in dot-prop/index.js

I think it has something to do with this

> `delete()` is a method on the main export. It's not an export itself though.

I don't think that [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) consider it to be that way since you are typing out `module.exports.get = ...`, `module.exports.delete = ...`. I made a quick test which demonstrates the issue. This file doesn't work:

```js
module.exports.get = function () {
  return 1
}

module.exports.delete = function () {
  return 2
}
```

But this file works great:

```js
module.exports = {
  get () {
    return 1
  },
  delete () {
    return 2
  }
}
```

Would you be open to switching to the latter style?

**Comment by SamVerschueren** [comment]
Ideally this should be fixed by Rollup itself though. Might be a bug, but might be intended as well. Care to open an issue there first and link this one?

**Comment by LinusU** [comment]
I have opened an issue here: https://github.com/rollup/rollup-plugin-commonjs/issues/130

But I think that this is intended behavior, since setting values on the `exports` object feels to me like you want to export separate things instead of one object.

i.e.

CommonJS | ES Modules
----- | -----
`exports.blah = function () {}` | `export function blah () {}`
`module.exports = { ... }` | `export default { ... }`

**Comment by stevemao** [comment]
I changed my mind now and I kinda think it's not an issue with this module. Although I'm not really opposing to change the name to `del`, I vote to close this issue.

**Comment by LinusU** [comment]
@sindresorhus Would you accept a pull request that changes from `exports.foo = ...; exports.bar = ...;` to `module.exports = { foo: ..., bar: ... }`? That would resolve the issue and I think makes the intended "delete() is a method on the main export. It's not an export itself though." more clear...

**Comment by stevemao** [comment]
> exports.foo = ...; exports.bar = ...; to module.exports = { foo: ..., bar: ... }

They should be exactly the same it's definitely a problem with the transpiler... 😀 
There are many modules that `exports` like that. You'd then need to change all of them then.

**Comment by LinusU** [comment]
It's not a problem per se. It's a decision that has been made by rollup.

It works great for most modules, the only small hiccup is that when you use the `exports.` notation you cannot have an export named `delete` (or any other keyword).

> They should be exactly the same

Not technically true since it change the reference to the export object and creates a new object, instead of adding properties to an already existing object...

**Comment by stevemao** [comment]
@SamVerschueren @sindresorhus thoughts?

**Comment by SamVerschueren** [comment]
@LinusU Have you tried doing something like this?

```js
module.exports['delete'] = {};
```

Does that work?

**Comment by LinusU** [comment]
@SamVerschueren To clarify again, I no longer want the name changed. The only change I want is to change how the functions are exported:

This is the only change that I want:

```diff
 	return parts;
 }
 
-module.exports.get = (obj, path, value) => {
+module.exports = {
+	get (obj, path, value) {
 		if (!isObj(obj) || typeof path !== 'string') {
 			return obj;
 		}
@@ -48,9 +49,9 @@ module.exports.get = (obj, path, value) => {
 		}
 
 		return obj;
-	};
+	},
 
-module.exports.set = (obj, path, value) => {
+	set (obj, path, value) {
 		if (!isObj(obj) || typeof path !== 'string') {
 			return;
 		}
@@ -70,9 +71,9 @@ module.exports.set = (obj, path, value) => {
 
 			obj = obj[p];
 		}
-	};
+	},
 
-module.exports.delete = (obj, path) => {
+	delete (obj, path) {
 		if (!isObj(obj) || typeof path !== 'string') {
 			return;
 		}
@@ -93,9 +94,9 @@ module.exports.delete = (obj, path) => {
 				return;
 			}
 		}
-	};
+	},
 
-module.exports.has = (obj, path) => {
+	has: (obj, path) {
 		if (!isObj(obj) || typeof path !== 'string') {
 			return false;
 		}
@@ -115,4 +116,5 @@ module.exports.has = (obj, path) => {
 		}
 
 		return true;
+	}
 };
```

This is needed because of a decision to treat `module.exports.get = ...; module.exports.set = ...;` as `export const get = ...; export const set = ...;` and `module.exports = { get: ..., set: ... };` as `export default { get: ..., set: ... };`.

This could be done in a patch release and there should be no impact at all for Node.js or browserify users :)

**Comment by LinusU** [comment]
I have a commit ready here and would be happy to open a pull request: https://github.com/sindresorhus/dot-prop/compare/master...LinusU:patch-2

**Comment by sindresorhus** [comment]
@LinusU Like Sam said, we're just tired of all the churn from users expecting fully working code to change because of their favorite tooling being "broken". But sure, looks like a simple change, so why not.

**Comment by LinusU** [comment]
Thank you ❤️ 

I totally understand and agree, as module authors we shouldn't have to deal with this, and there will always be some problems. I really appreciate you accepting this as it makes my life a bit easier.

In a few years, I hope that this particular issues will be solved by ES Modules, but until then we'll just have to hang in there 🚀

I've submitted #34 with this change. It also fixes a linting issue that I think was introduced by a newer version of xo. Stay awesome 🤘
