### ISSUE TITLE
Provide built library

### ISSUE THREAD

**Issue by jacob-israel-turner** [sindresorhus/dot-prop#37]
We cannot currently use this in our codebase, as we don't run `node_modules` through Babel, and we must target older browsers.  `let` and `const` don't work for us.

Can this be transpiled before being published to NPM?

**Comment by sindresorhus** [comment]
No. Reasoning: https://github.com/sindresorhus/file-type/issues/70#issuecomment-268853935

**Comment by jacob-israel-turner** [comment]
Fair enough. I liked your suggestion to have a tool check the target of dependencies, and build when necessary.
