### ISSUE TITLE
Uglify issues with this repo

### ISSUE THREAD

**Issue by msafari** [sindresorhus/dot-prop#44]
This repo seems to be published without transpiling source-code. 
This causes a painful issue with production facing applications that uglify their code since uglify doesn't work with ES6 yet.
I was able to get around the bug by transpiling this dependency with webpack before uglifying. But ideally, I think it's always better to do the transformation before publishing.

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by msafari** [comment]
Thanks for your suggestion! I already resolved the issue on my end by applying this rule to webpack so it only transpiles this specific dependency. I was trying to see if this project will ever try to transpile itself, which from what you're saying looks like it won't.

```
rules: [{
      test: /\.js$/,
      exclude: /node_modules\/(?!dot-prop)\/*/,
      loader: 'babel-loader'
    }]
```

Just mentioning it here for others who may not want to add an extra plugin.
