### ISSUE TITLE
SecurityHotfix v4.2.0

### ISSUE THREAD

**Issue by martinoppitz** [sindresorhus/dot-prop#59]
See https://snyk.io/test/npm/dot-prop/4.2.0

Thank you

**Comment by sindresorhus** [comment]
This was fixed in `5.1.1`. I don't have any plans to backport it to `4.x.x`.

**Comment by sindresorhus** [comment]
Update: https://github.com/sindresorhus/dot-prop/issues/63#issuecomment-674513678
