### ISSUE TITLE
Version 4.2.0 is default in nodejs

### ISSUE THREAD

**Issue by dominopetter** [sindresorhus/dot-prop#62]
Not sure if this is the right forum for this but the old and insecure version of dot-prop 4.2.0 is still being installed in nodejs causing some security issues. Trying to update it does not work due to some dependencies. Who should I contact about this? I opened an issue here also but no clue how to deal with these types of issues: https://github.com/nodesource/distributions/issues/1096

**Comment by sindresorhus** [comment]
https://github.com/nodesource/distributions/issues/1096 would be the best place to deal with this. The problem was already fixed a long time ago here.

**Comment by sindresorhus** [comment]
Update: https://github.com/sindresorhus/dot-prop/issues/63#issuecomment-674513678
