### ISSUE TITLE
escape()

### ISSUE THREAD

**Issue by kakserpom** [sindresorhus/dot-prop#83]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `dot-prop@6.0.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/dot-prop/index.js b/node_modules/dot-prop/index.js
index aa9c5bb..57a49b5 100644
--- a/node_modules/dot-prop/index.js
+++ b/node_modules/dot-prop/index.js
@@ -134,5 +134,9 @@ module.exports = {
 		}
 
 		return true;
+	},
+
+	escape(prop) {
+		return prop.replace(/\./g, '\\.')
 	}
 };
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sindresorhus** [comment]
A good pull request with docs, tests, and types would be welcome. I think the method should be called `escapeKeyPath`.

**Comment by Richienb** [comment]
To futureproof this, it would be a good idea to segment the path and then reassemble an escaped version from there. Especially with #82
