### ISSUE TITLE
Array length doesn't change after deleting item

### ISSUE THREAD

**Issue by selfagency** [sindresorhus/dot-prop#85]
After using `dotProp.delete()` to remove an item from an array of objects, I'm finding that the array length stays the same. Shouldn't the count automatically update when an item is deleted? If not, how can I work around it to get the right length?

```
0: (...)
1: Object
  children: Array(1)
    0:
      children: Array(2)
        0: {__ob__: Observer}
        length: 2
```

**Comment by sindresorhus** [comment]
This package doesn't actually support arrays. It's only implicitly supported as arrays are just objects.

**Comment by sindresorhus** [comment]
Duplicate of #71
