### ISSUE TITLE
How to access data with array

### ISSUE THREAD

**Issue by mikeerickson** [sindresorhus/dot-prop#87]
Trying to do something like this:

```javascript
const dotProp = require('dot-prop')

const data = {
  data: [{ price: 1234 }],
}

const result = dotProp.get(data, 'data[0].price')
```

But result is always `undefined`

Is this possible with this library? Or perhaps I should look at an alternative?

**Comment by sindresorhus** [comment]
It's coming soon: https://github.com/sindresorhus/dot-prop/pull/82

**Comment by mikeerickson** [comment]
Hey @sindresorhus any movement on this issue?  I have a hack working, but I would much rather roll with something I can trust.
