### ISSUE TITLE
`deepKeys` helper?

### ISSUE THREAD

**Issue by mmkal** [sindresorhus/dot-prop#93]
Hi, I've implemented this a couple of times but wondered whether there'd be any interest in including it in this library:

```ts
const obj = { foo: { bar: 1, baz: { 'a.b': 2 } } }

deepKeys(obj) // ['foo.bar', 'foo.baz.a\\.b']
```

Worth doing here because the `\\.` is a convention invented by dot-prop (as far as I'm aware), so it makes sense for `deepKeys` to return paths that `getProperty` will later understand.

**Comment by sindresorhus** [comment]
What's the use-case?

**Comment by mmkal** [comment]
One example: when you have data in nested object form, that needs to be used somewhere that only accepts key/value pairs. e.g. get valid parameter values for text templates like `` `Hello, {user.name.firstName}` ``, or if you need to send nested text content to a translation service that only accepts key-value pairs.

Another one: it makes it easy to edit "leaf" nodes of arbitrarily complex objects without having to write easy-to-get-wrong recursive functions (because this library will have already covered the edge cases):

```ts
const trimStringValues = <T extends {}>(obj: T): T => {
  const keys = deepKeys(obj)
  const newObj: any = {}
  keys.forEach(k => {
    const original = getProperty(obj, k)
    setProperty(newObj, k, typeof k === 'string' ? k.slice(0, 10) : k)
  })
  return newObj as T
}
```

I haven't looked into the implementation of this library, but maybe it could even be helpful internally.

**Comment by sindresorhus** [comment]
Alright. I'm ok with adding this. But the one that adds it should make sure to also document the mentioned use-cases for it.
