### ISSUE TITLE
Netlify build failing with   Error: [ERR_REQUIRE_ESM]: Must use import to load ES Module: /path/node_modules/dot-prop/index.js

### ISSUE THREAD

**Issue by samgermain** [sindresorhus/dot-prop#97]
The issue is described on this [SO post](https://stackoverflow.com/questions/71835131/why-would-non-updated-npm-dependencies-cause-new-errors)

[This commit](https://github.com/sindresorhus/dot-prop/commit/5a8324219dcb6bc3e793457a8e8ed27cd3e3daf8) is the culprit apparently

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by samgermain** [comment]
@sindresorhus What should I do? `gatsby` isn't mentioned in that gist. I dont think that gist answers my question

**Comment by sindresorhus** [comment]
Your project must be ESM. The gist explains how. I cannot document every possible build system. Your question is better asked on the Netlify support forums.
